import { t } from "elysia";

export const vs = {
  uuid: t.String({ maxLength: 64 }),
  token: t.String({ maxLength: 256 }),
  csrfToken: t.Optional(t.String({ maxLength: 256 })),
  email: t.String({ maxLength: 254 }),
  password: t.String({ minLength: 1, maxLength: 128 }),
  firstName: t.Optional(t.String({ maxLength: 100 })),
  lastName: t.Optional(t.String({ maxLength: 100 })),
  phone: t.Optional(t.String({ maxLength: 30 })),
  country: t.Optional(t.String({ maxLength: 3 })),
  postalCode: t.String({ maxLength: 20 }),
  city: t.String({ maxLength: 100 }),
  state: t.String({ maxLength: 100 }),
  line1: t.String({ maxLength: 300 }),
  line2: t.Optional(t.String({ maxLength: 300 })),
  neighborhood: t.Optional(t.String({ maxLength: 100 })),
  reference: t.Optional(t.String({ maxLength: 300 })),
  notes: t.Optional(t.String({ maxLength: 1000 })),
  reason: t.String({ maxLength: 500 }),
  sku: t.String({ maxLength: 50 }),
  skuId: t.String({ maxLength: 64 }),
  variantLabel: t.Optional(t.String({ maxLength: 100 })),
  productName: t.String({ maxLength: 200 }),
  productDesc: t.Optional(t.String({ maxLength: 5000 })),
  categoryId: t.Optional(t.String({ maxLength: 64 })),
  tagName: t.String({ maxLength: 50 }),
  tagColor: t.Optional(t.String({ maxLength: 7, pattern: "^#[0-9a-fA-F]{6}$" })),
  tagDesc: t.Optional(t.String({ maxLength: 500 })),
  taskTitle: t.String({ maxLength: 200 }),
  taskDesc: t.Optional(t.String({ maxLength: 2000 })),
  noteBody: t.String({ maxLength: 5000 }),
  interactionSummary: t.String({ maxLength: 1000 }),
  status: t.String({ maxLength: 30 }),
  trackingCode: t.String({ maxLength: 100 }),
  trackingUrl: t.Optional(t.String({ maxLength: 2048 })),
  carrier: t.Optional(t.String({ maxLength: 100 })),
  promotionName: t.String({ maxLength: 200 }),
  discountValue: t.String({ maxLength: 10 }),
  attributeValue: t.String({ maxLength: 500 }),
  quantity: t.String({ maxLength: 10 }),
  delta: t.String({ maxLength: 10 }),
  orderId: t.String({ maxLength: 64 }),
};
